# Generated by Django 5.2 on 2025-05-17 09:29

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KG')),
                ('first_name', models.CharField(blank=True, max_length=60)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(140)])),
                ('profile_picture', models.ImageField(upload_to='profile_images/')),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=32)),
                ('role', models.CharField(choices=[('Admin', 'admin'), ('Reception', 'reception'), ('Doctor', 'doctor')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmailLoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctor_image/')),
                ('medical_license', models.CharField(max_length=50)),
                ('bonus', models.CharField(blank=True, max_length=27, null=True)),
                ('cabinet', models.CharField(blank=True, max_length=5, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_doctor', to='crm_app.department')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speciality_doctor', to='crm_app.speciality')),
            ],
            options={
                'verbose_name': 'Doctor',
            },
            bases=('crm_app.userprofile',),
        ),
        migrations.CreateModel(
            name='DoctorServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_service', models.CharField(max_length=256)),
                ('price', models.PositiveIntegerField(default=0)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('salary_doctor', models.PositiveSmallIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_services', to='crm_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('birthday', models.DateField()),
                ('started_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('gender_patient', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=32)),
                ('status_patient', models.CharField(choices=[('Живая очередь', 'Живая очередь'), ('Предзапись', 'Предзапись'), ('Отмененные', 'Отмененные')], max_length=32)),
                ('created_date', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_patient', to='crm_app.department')),
                ('doctor_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_doctor', to='crm_app.doctorservices')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_patient', to='crm_app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('change', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта')], default='cash', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KG')),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.department')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.doctorservices')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_customer', to='crm_app.patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_customer', to='crm_app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_analytics', to='crm_app.doctorservices')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_analytics', to='crm_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departament_price_list', to='crm_app.department')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_service', to='crm_app.doctorservices')),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speciality_reception', to='crm_app.speciality')),
            ],
            options={
                'verbose_name': 'Reception',
            },
            bases=('crm_app.userprofile',),
        ),
        migrations.AddField(
            model_name='patient',
            name='reception',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reception_patient', to='crm_app.reception'),
        ),
        migrations.CreateModel(
            name='HistoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('record', models.CharField(choices=[('был в приеме', 'был в приеме'), ('в ожидании', 'в ожидании'), ('отменен', 'отменен')], default='в ожидании', max_length=32)),
                ('description', models.TextField()),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departament_history', to='crm_app.department')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='crm_app.customerrecord')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_history', to='crm_app.doctorservices')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_history', to='crm_app.patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_history', to='crm_app.doctor')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reception_history', to='crm_app.reception')),
            ],
        ),
        migrations.AddField(
            model_name='customerrecord',
            name='reception',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reception_customer', to='crm_app.reception'),
        ),
    ]
