# Generated by Django 5.2 on 2025-05-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='medical_linense',
            new_name='medical_license',
        ),
    ]
