# Generated by Django 5.2 on 2025-05-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorservices',
            name='doctor_service',
            field=models.CharField(max_length=32),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
