# Generated by Django 5.2 on 2025-05-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_alter_doctor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='full_name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
