# Generated by Django 5.2 on 2025-05-13 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_emaillogincode_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speciality_reception', to='crm_app.speciality'),
        ),
    ]
